---
title: "Analysis of the Effects of Weather on Mortality in Metropolitan Areas"
output: github_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

Madhu Avula, Nick DeReus, Jacob Johnson, Brianna Norman

# This document will eventually contain the final report of this project. For now it is a place for thoughts and structuring

## Introduction

The weather has outstanding impacts on the daily lives of individuals, this project seeks to research the weather's impact on mortality rates to better understand the necessity and impact of weather resilience as well as the potential dangers of ongoing climate change.

We shall endeavor to answer the following questions:

1. Are there seasonal trends in mortality rates? Do different regions experience these impacts differently?
```{R} 
allData <- read.csv("Data Files/combined_TAVGxMortality_Data.csv")
```


### Create lists of the cities that I'm making observations on
```{R}
myStatesList <- c('FL', 'CA', 'KS', 'CO')
myCitiesList <- c('Miami', 'Fresno', 'Wichita', 'Colorado Springs')
```

### Filter data down to focused cities
### Deaths seem to be higher on average in the Winter Months
### Fresno in Region 3, specifically, saw jumps in mortality November through March each year
### Miami, in Region 2, reported a jump in mortality count between June and July in years 
```{R}
myCitiesData <- allData %>%
  filter(State %in% myStatesList) %>% filter(City %in% myCitiesList)

monthlyDeathsSummed<- myCitiesData %>%
  group_by(Month, Year, City) %>%
  summarise(total = sum(All.Deaths))

ggplot(monthlyDeathsSummed, aes(x=Month, y=total, color=City)) + 
  geom_point() + 
  facet_wrap(~Year, scales="free_x") +
  labs(
    title = "Total Deaths by Month",
    x = "Month",
    y = "Total Deaths"
  )
```



2. How much of an impact does temperature have on mortality? Do different regions experience these impacts differently?

```{R}
ourStatesList <- c('FL', 'CA', 'KS', 'CO', 'TX', 'TN', 'WA', 'IN', 'AZ', 'AR', 'IN', 'MA', 'NY', 'MN', 'WI')
ourCitiesList <- c('Miami', 'Fresno', 'Wichita', 'Colorado Springs', 'Pheonix', 'Little Rock', 'Evansville', 'Boston', 'Houston', 'Memphis', 'Seattle', 'Indianapolis', 'Utica', 'Minneapolis', 'Saint Paul', 'Milwaukee')

ourCitiesData <- allData %>%
  filter(State %in% ourStatesList) %>% filter(City %in% ourCitiesList)
```
### The higher end of maximum temperatures during a month generally sees more deaths than the lower end of maximum temperatures, being that the total deaths for our observed cities was below 1e+05 at average maximum temperature of 25, whereas the total deaths was closer to 8e+05 when the average maximum temperature was 85.
#### Plot of the mean of the maximum monthly temperature plotted against the total deaths occurring at those temperatures
```{R}
ggplot(ourCitiesData, aes(x=TMAX_Mean, weight=All.Deaths)) + geom_histogram(bins=15)
```

### The most deaths occurred during times where the average minimum temperature was between 45 and 60, which is likely the minimum from the days with high maximum temperatures. It is expected that colder regions will see higher mortality counts in lower temperatures when observed outside of the other regions.
#### Plot of the mean of the minimum monthly temperature plotted against the total deaths occurring at those temperatures
```{R}
ggplot(ourCitiesData, aes(x=TMIN_Mean, weight=All.Deaths)) + geom_histogram(bins=15)
```
### Region 2 sees the highest death counts at maximum temperatures near 90, with death counts sharply increasing as the max temperature approaches that value. This region's mortality rates do not seem as affected by temperatures below 35, likely due to a generally higher climate and not seeing temperatures that low.
### Region 6 confirms the earlier held suspicion of a colder climate holding a higher mortality rate at lower temperatures than that of higher climates. This region has two mortality rate spikes: One where the max temperature approaches 75, and another where it is close to 30. However, the mortality rate seems to be fairly consistent at minimum temperatures between 35 and 60 in region 6

#### Plot of the mean of the maximum monthly temperature plotted against the total deaths occurring at those temperatures, grouped by Region
```{R}
ggplot(ourCitiesData, aes(x=TMAX_Mean, weight=All.Deaths)) + geom_histogram(bins=15) + facet_wrap(~region)
```
#### Plot of the mean of the minimum monthly temperature plotted against the total deaths occurring at those temperatures
```{R}
ggplot(ourCitiesData, aes(x=TMIN_Mean, weight=All.Deaths)) + geom_histogram(bins=15) + facet_wrap(~region)
```

3. Are different age groups affected differently? What age groups are most at risk?

4. Which kinds of weather events have the greatest impacts on mortality? (Extreme heat, cold, ice, flooding)

5. 

## Data

We had to unite multiple datasets to answer these question, one from the CDC which contains weekly mortality data for a selection of 122 cities accessed here: https://data.cdc.gov/dataset/Deaths-in-122-U-S-cities-1962-2016-122-Cities-Mort/mr8w-325u/about_data . The second dataset contains daily weather summaries from weather stations from all over the US, the weather station which best represents a city from our mortality dataset has to be linked up with their city and the rest could be dropped.

### Data Values and Structure

#### Deaths in 122 US Cities

* Year - 
* WEEK - 
* Week Ending Date - 
* State -
* City -
* Pneumonia.and.Influenza.Deaths
* All.Deaths -
* <1 year (all cause deaths) -
* 1-24 years (all cause deaths) -
* 25-44 years (all cause deaths) -
* 45-64 years (all cause deaths) -
* 65+ years (all cause deaths) - 

#### NOAA CDO Daily Summaries

  This dataset is quite detailed, but we're mostly interested in three variables:
  
  1. TAVG - Average temperature.
  2. TMAX - Maximum Temperature.
  3. TMIN - Minimum Temperature.

* STATION - Identifying weather station code
* NAME - Weather station name
* DATE - Date of summary
* WT03 - Thunder
* WT04 - Ice pellets, sleet, snow pellets, or small hail"
* PRCP - Precipitation
* WT05 - Hail (may include small hail)
* WSFM - Fastest mile wind speed
* WT06 - Glaze or rime
* WT07 - Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction
* WT08 - Smoke or haze
* SNWD - Snow depth
* WT09 - Blowing or drifting snow
* WDF1 - Direction of fastest 1-minute wind
* WDF2 - Direction of fastest 2-minute wind
* WDF5 - Direction of fastest 5-second wind
* WT10 - Tornado, waterspout, or funnel cloud"
* PGTM - Peak gust time
* WT11 - High or damaging winds
* TMAX - Maximum temperature
* WT13 - Mist
* FRGT - Top of frozen ground layer
* WSF2 - Fastest 2-minute wind speed
* FMTM - Time of fastest mile or fastest 1-minute wind
* ACMH - Average cloudiness midnight to midnight from manual observations
* WSF5 - Fastest 5-second wind speed
* SNOW - Snowfall
* WDFG - Direction of peak wind gust
* WT14 - Drizzle
* ACSH - Average cloudiness sunrise to sunset from manual observations
* WT15 - Freezing drizzle
* WT16 - Rain (may include freezing rain, drizzle, and freezing drizzle)"
* WT17 - Freezing rain
* WT18 - Snow, snow pellets, snow grains, or ice crystals
* WT19 - Unknown source of precipitation
* WSF1 - Fastest 1-minute wind speed
* AWND - Average wind speed
* WT21 - Ground fog
* WSFG - Peak gust wind speed
* WT22 - Ice fog or freezing fog
* WT01 - Fog, ice fog, or freezing fog (may include heavy fog)
* WESD - Water equivalent of snow on the ground
* WT02 - Heavy fog or heaving freezing fog (not always distinguished from fog)
* PSUN - Daily percent of possible sunshine for the period
* TAVG - Average Temperature.
* TMIN - Minimum temperature
* WDFM - Fastest mile wind direction
* TSUN - Total sunshine for the period
